### ISSUE TITLE
Keeping killProgram()

### ISSUE THREAD

**Issue by gazie91** [lsalazar1/pvPark#23]
We can keep the killProgram() method, but it needs to save the data from the collection possibly in an xml file before deleting it

**Comment by rouoba** [comment]
Ok I’ll look into that

**Comment by rouoba** [comment]
It looks like there is no definition for the drop() function that’s in the body of killProgram()?!

**Comment by lsalazar1** [comment]
> It looks like there is no definition for the drop() function that’s in the body of killProgram()?!

Lol this is a great question. The drop() function comes from the pymongo module that's declared at the very top.
