### ISSUE TITLE
DeprecationWarning Appearing

### ISSUE THREAD

**Issue by lsalazar1** [lsalazar1/pvPark#32]
When the command `npm run server` is run to set up the backend locally,  this message will appear in the terminal:

> (node:14612) DeprecationWarning: collection.ensureIndex eIndex is deprecated. Use createIndexes instead. 
MongoDB connected

Possible fixes are to add these fields as options in connectDB.js
- useCreateIndex: true
- useFindAndModify: false

**Comment by mbghazi** [comment]
Added the following: 

useCreateIndex: true
useFindAndModify: false
