### ISSUE TITLE
Update Needed for Python Code

### ISSUE THREAD

**Issue by lsalazar1** [lsalazar1/pvPark#34]
**Is your feature request related to a problem? Please describe.**
Issue #31 will require us to redesign what a BSON object would look like for a parking lot's collection. At the moment, the requests our python code is storing in our database, isn't matching up with what we require for to properly fetch for our app.

**Describe the solution you'd like**
Muhammad and I will do a couple things. First, we would like to test the driver code for our RPi to see if it's sending the correctly formatted data. Second, we would like to know from the frontend team what parking spots they plan on tracking, so we can make the necessary routes for it.

**Comment by lsalazar1** [comment]
@rouoba @gazie91 How does this endpoint sound "api/raspberry" and y'all can name it however lol

**Comment by rouoba** [comment]
That sounds good. It's explicit enough to know which interface we'll be getting the data from.
