### ISSUE TITLE
Certificate handling in Heroku

### ISSUE THREAD

**Issue by rouoba** [lsalazar1/pvPark#58]
**Describe the bug**
The certificate is not always valid, so trying to display a webpage would sometimes display a non valid certificate issue, and request the user to choose if they would like to access the "unsecured website"

**Expected behavior**
The data should be always accessible through the website

**Comment by lsalazar1** [comment]
So our server already has a legitimate SSL cert. The problem most likely lies with our school's network. Their network is viewing our web server as a malicious site. For future demos, we may do one of the following:

1. Host it locally, however we would have to change the IP address to the server every time we activate it

2. Use a hotspot during demos to skip over the school's wifi
