### ISSUE TITLE
Errors/Warnings Encountered during MAS Visit

### ISSUE THREAD

**Issue by lsalazar1** [lsalazar1/pvPark#62]
**Describe the bug**
Upon running the Raspberry Pi, the sensors will sometimes get bad readings. Here are the two types of errors we are receiving:

- AttributeError: saying that the pins aren't reading correctly. Another error we'll get is a 

- RuntimeError: After a couple minutes of running, the program will throw this error. The message that comes along with it says that it can't start a new thread.

These will cause the front-facing app to show the wrong output.

**To Reproduce**
1. In terminal: `cd Developer/pvPark/python`
2. `git pull origin master`
3. `git checkout master`
4. `python3 main.py`
5. Review shell output for errors

**Expected behavior**
Python program should return an accurate reading of sensors.

**Screenshots**
![IMG_20200229_142309](https://user-images.githubusercontent.com/42328472/75700856-5b8cb380-5c78-11ea-95d7-31b2996ed688.jpg)
RuntimeError shows that the program cannot create anymore threads

**Desktop (please complete the following information):**
 - OS: Raspbian

**Comment by lsalazar1** [comment]
![FireShot Capture 147 - 13  API - Input Devices — Gpiozero 1 5 1 Documentation_ - gpiozero readthedocs io](https://user-images.githubusercontent.com/42328472/75736503-f7dba800-5cc2-11ea-8106-ad11d87bff6a.png)
 Possible fix? Maybe we can trigger a reading if a certain event happens like when a vehicle enters or leaves the area being tracked?

**Comment by lsalazar1** [comment]
![Capture](https://user-images.githubusercontent.com/42328472/75743365-59f1d880-5cd6-11ea-8b6a-d66c2a14f0ad.PNG)
I was playing around with threads in python today. I learned that you can't restart the same thread more than once.

I was thinking what if we assigned a sensor to each thread... Any thoughts?

**Comment by rouoba** [comment]
I would say that makes sense unless there's a way to put a thread in a dormant state. We have to make sure at the end of each loop, the memory is properly freed and also try changing sensors/ wires / hardware in general in case we do have a faulty connection.

**Comment by lsalazar1** [comment]
Not enough time lol
